import { expect, test, type Page } from '@playwright/test'
import { registerViaUi, uniqueCredentials } from '../support/auth'
import { chooseOption, expectNoHorizontalOverflow, gotoDestination, pickDate } from '../interface/support'
import { collectRuntimeIssues, expectNoRuntimeIssues } from '../core-daily-loop/support'

const today = '2026-08-13'

async function createFood(page: Page, name: string, calories = '100'): Promise<void> {
  const form = page.getByRole('form', { name: 'Create food' })
  await form.getByLabel('Food name').fill(name)
  await chooseOption(form, 'Basis', 'Grams')
  await form.getByLabel('Calories per 100').fill(calories)
  await form.getByLabel('Protein per 100').fill('10')
  await form.getByLabel('Fat per 100').fill('2')
  await form.getByLabel('Carbohydrate per 100').fill('20')
  await form.getByLabel('Food quality').fill('80')
  await form.getByRole('button', { name: 'Create food' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Food created.' })).toBeVisible()
}

test('private foods and composite recipe have a complete lifecycle', async ({ page }, testInfo) => {
  test.setTimeout(90_000)
  await registerViaUi(page, uniqueCredentials(testInfo, 'NutritionCatalogue'), { redirectTo: '/nutrition' })
  const issues = collectRuntimeIssues(page)
  await expect(page.getByRole('heading', { name: 'Nutrition', exact: true })).toBeVisible()
  await expect(page.getByRole('list', { name: 'Food catalogue' })).toContainText('Plain water')
  await expect(page.getByRole('listitem', { name: 'Plain water' })).not.toContainText('Edit')

  await createFood(page, 'Grain')
  await createFood(page, 'Nut', '300')
  let grain = page.getByRole('listitem', { name: 'Grain' })
  await grain.getByRole('button', { name: 'Edit Grain' }).click()
  const editor = page.getByRole('form', { name: 'Edit Grain' })
  await editor.getByLabel('Food name').fill('Rolled grain')
  await editor.getByLabel('Protein per 100').fill('12')
  await editor.getByRole('button', { name: 'Save food' }).click()
  grain = page.getByRole('listitem', { name: 'Rolled grain' })
  await expect(grain).toContainText('P 12.000')
  await grain.getByRole('button', { name: 'Archive Rolled grain' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Food archived.' })).toBeVisible()
  await page.getByRole('radio', { name: 'Archived foods' }).click()
  await page.getByRole('listitem', { name: 'Rolled grain' }).getByRole('button', { name: 'Restore Rolled grain' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Food restored.' })).toBeVisible()
  await page.getByRole('radio', { name: 'Active foods' }).click()

  const recipe = page.getByRole('form', { name: 'Create recipe' })
  await recipe.getByLabel('Recipe name').fill('Grain bowl')
  await recipe.getByRole('button', { name: 'Add component' }).click()
  await chooseOption(recipe, 'Component 1', 'Rolled grain')
  await recipe.getByLabel('Component 1 grams').fill('100')
  await recipe.getByRole('button', { name: 'Add component' }).click()
  await chooseOption(recipe, 'Component 2', 'Nut')
  await recipe.getByLabel('Component 2 grams').fill('300')
  await recipe.getByRole('button', { name: 'Create recipe' }).click()
  const card = page.getByRole('listitem', { name: 'Grain bowl' })
  await expect(card).toContainText('250.000 kcal / 100 g')
  await expect(card).toContainText('80.00')
  await card.getByRole('button', { name: 'Edit recipe Grain bowl' }).click()
  const recipeEditor = page.getByRole('form', { name: 'Edit recipe Grain bowl' })
  await recipeEditor.getByLabel('Description').fill('Editable whole-food recipe')
  await recipeEditor.getByRole('button', { name: 'Remove component 2' }).click()
  await recipeEditor.getByRole('button', { name: 'Add component' }).click()
  await chooseOption(recipeEditor, 'Component 2', 'Nut')
  await recipeEditor.getByLabel('Component 2 grams').fill('100')
  await recipeEditor.getByRole('button', { name: 'Save recipe' }).click()
  await expect(card).toContainText('200.000 kcal / 100 g')
  await card.getByRole('button', { name: 'Archive Grain bowl' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Recipe archived.' })).toBeVisible()
  await page.getByRole('radio', { name: 'Archived recipes' }).click()
  await page.getByRole('listitem', { name: 'Grain bowl' }).getByRole('button', { name: 'Restore Grain bowl' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Recipe restored.' })).toBeVisible()
  await page.getByRole('radio', { name: 'Active recipes' }).click()
  await expect(card).toBeVisible()
  await page.reload()
  await expect(page.getByRole('listitem', { name: 'Grain bowl' })).toBeVisible()
  await expectNoHorizontalOverflow(page)
  expectNoRuntimeIssues(issues)
})

test('meal snapshots combine food recipe beverage hydration and stable target', async ({ page }, testInfo) => {
  test.setTimeout(90_000)
  await registerViaUi(page, uniqueCredentials(testInfo, 'NutritionMeal'), { redirectTo: '/nutrition' })
  await createFood(page, 'Grain')

  const beverage = page.getByRole('form', { name: 'Create food' })
  await beverage.getByLabel('Food name').fill('Recovery drink')
  await chooseOption(beverage, 'Basis', 'Millilitres')
  await beverage.getByLabel('Beverage').check()
  await beverage.getByLabel('Calories per 100').fill('50')
  await beverage.getByLabel('Protein per 100').fill('2')
  await beverage.getByLabel('Fat per 100').fill('0')
  await beverage.getByLabel('Carbohydrate per 100').fill('10')
  await beverage.getByLabel('Hydration ratio').fill('0.8')
  await beverage.getByRole('button', { name: 'Create food' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Food created.' })).toBeVisible()

  const meal = page.getByRole('form', { name: 'Log meal' })
  await pickDate(page, 'Consumed date', today)
  await meal.getByLabel('Meal name').fill('Breakfast')
  await chooseOption(meal, 'Category', 'Breakfast')
  await meal.getByRole('button', { name: 'Add entry' }).click()
  await chooseOption(meal, 'Entry 1', 'Grain')
  await meal.getByLabel('Entry 1 quantity').fill('200')
  await meal.getByRole('button', { name: 'Add entry' }).click()
  await chooseOption(meal, 'Entry 2', 'Recovery drink')
  await meal.getByLabel('Entry 2 quantity').fill('250')
  await meal.getByRole('button', { name: 'Add entry' }).click()
  await chooseOption(meal, 'Entry 3', 'Plain water')
  await meal.getByLabel('Entry 3 quantity').fill('500')
  await meal.getByRole('button', { name: 'Log meal' }).click()

  const progress = page.getByRole('region', { name: 'Nutrition progress' })
  await expect(progress).toContainText('325 kcal')
  await expect(progress).toContainText('700 ml')
  await expect(page.getByRole('region', { name: 'Daily target' })).toContainText('Stable reference')
  const card = page.getByRole('listitem', { name: 'Breakfast' })
  await card.getByRole('button', { name: 'Edit Breakfast' }).click()
  const mealEditor = page.getByRole('form', { name: 'Edit Breakfast' })
  await mealEditor.getByLabel('Entry 1 quantity').fill('250')
  await mealEditor.getByLabel('Note').fill('Corrected after weighing')
  await mealEditor.getByRole('button', { name: 'Remove entry 3' }).click()
  await mealEditor.getByRole('button', { name: 'Remove entry 2' }).click()
  await mealEditor.getByRole('button', { name: 'Add entry' }).click()
  await chooseOption(mealEditor, 'Entry 2', 'Plain water')
  await mealEditor.getByLabel('Entry 2 quantity').fill('500')
  await mealEditor.getByRole('button', { name: 'Save meal' }).click()
  await expect(progress).toContainText('250 kcal')
  await expect(progress).toContainText('500 ml')
  await page.reload()
  await expect(progress).toContainText('250 kcal')
  await card.getByRole('button', { name: 'Edit Breakfast' }).click()
  await expect(page.getByRole('form', { name: 'Edit Breakfast' }).getByLabel('Note')).toHaveValue('Corrected after weighing')
  await expectNoHorizontalOverflow(page)
})

test('Today and Review present the Nutrition-owned selected-day summary', async ({ page }, testInfo) => {
  test.setTimeout(60_000)
  await registerViaUi(page, uniqueCredentials(testInfo, 'NutritionSurfaces'), { redirectTo: '/nutrition' })
  await createFood(page, 'Grain')
  const meal = page.getByRole('form', { name: 'Log meal' })
  await meal.getByLabel('Meal name').fill('Breakfast')
  await meal.getByRole('button', { name: 'Add entry' }).click()
  await chooseOption(meal, 'Entry 1', 'Grain')
  await meal.getByLabel('Entry 1 quantity').fill('200')
  await meal.getByRole('button', { name: 'Log meal' }).click()

  await gotoDestination(page, 'Today')
  await pickDate(page, 'Date', today)
  await expect(page.getByRole('region', { name: 'Nutrition summary' })).toContainText('200 kcal')
  await page.goto(`/review/${today}`)
  await expect(page.getByRole('region', { name: 'Nutrition summary' })).toContainText('200 kcal')
  await page.getByRole('link', { name: 'Open Nutrition' }).click()
  await expect(page).toHaveURL(new RegExp('/nutrition\\?date=2026-08-13'))
  await expect(page.getByRole('listitem', { name: 'Breakfast' })).toBeVisible()
})

test('workspace localizes EN RU UK and restores rejected writes on mobile', async ({ page }, testInfo) => {
  test.setTimeout(60_000)
  await registerViaUi(page, uniqueCredentials(testInfo, 'NutritionLocales'))
  await page.getByRole('button', { name: 'RU', exact: true }).click()
  await page.goto('/nutrition')
  await expect(page.getByRole('heading', { name: 'Питание', exact: true })).toBeVisible()
  await expect(page.getByRole('form', { name: 'Добавить продукт' })).toBeVisible()
  await page.getByRole('button', { name: 'UK', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Харчування', exact: true })).toBeVisible()
  const name = page.getByRole('form', { name: 'Додати продукт' }).getByLabel('Назва продукту')
  await name.focus()
  await expect(name).toBeFocused()

  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await page.route('**/api/nutrition/foods', async (route) => {
    if (route.request().method() === 'POST') {
      await route.fulfill({ status: 422, contentType: 'application/json', body: JSON.stringify({
        message: 'Food could not be saved.', errors: { name: ['Food could not be saved.'] },
      }) })
      return
    }
    await route.continue()
  })
  const form = page.getByRole('form', { name: 'Create food' })
  await form.getByLabel('Food name').fill('Must rollback')
  await form.getByRole('button', { name: 'Create food' }).click()
  await expect(page.locator('p[role="alert"]').filter({ hasText: 'Food could not be saved.' })).toBeVisible()
  await expect(page.getByRole('listitem', { name: 'Must rollback' })).toBeHidden()
  await expect(form.getByLabel('Food name')).toHaveValue('Must rollback')

  await page.getByTestId('quick-theme-toggle').click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  if (testInfo.project.name === 'mobile') {
    const button = form.getByRole('button', { name: 'Create food' })
    await button.scrollIntoViewIfNeeded()
    const box = await button.boundingBox()
    expect(box?.height ?? 0).toBeGreaterThanOrEqual(44)
  }
  await expectNoHorizontalOverflow(page)
})
