import { expect, test } from '@playwright/test'
import { registerViaUi, uniqueCredentials, xsrfHeader } from '../support/auth'
import { chooseOption, expectNoHorizontalOverflow, pickDate } from './support'

test('capture, finish and find a task without leaving the daily loop', async ({ page }, info) => {
  await registerViaUi(page, uniqueCredentials(info, 'DailyUX'))
  const navigation = page.getByRole('navigation', { name: 'Primary navigation' })
  await expect(navigation.getByRole('link', { name: 'Plan', exact: true })).toBeVisible()
  await expect(navigation.getByRole('link', { name: 'Tasks', exact: true })).toBeVisible()
  const form = page.getByRole('form', { name: 'Quick capture' })
  await form.getByRole('button', { name: 'Add', exact: true }).click()
  await expect(form.getByText('Give this item a name.')).toBeVisible()
  await form.getByRole('textbox').fill('Walk outside')
  await form.getByRole('button', { name: 'Add', exact: true }).click()
  await expect(page.getByText('Added to this day.', { exact: true })).toBeVisible()
  await expect(form.getByRole('textbox')).toHaveValue('')
  await expect(page.getByRole('listitem', { name: 'Walk outside', exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Complete Walk outside', exact: true }).click()
  await expect(page.getByText('Completed: Walk outside.', { exact: true })).toBeVisible()
  await page.reload()
  await expect(form).toBeVisible()
  await expect(page.getByRole('listitem', { name: 'Walk outside', exact: true })).toHaveCount(0)
  await navigation.getByRole('link', { name: 'Tasks', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Closed', exact: true })).toContainText('Walk outside')
  await expectNoHorizontalOverflow(page)
})

test('selected date follows capture and the link into the planner', async ({ page }, info) => {
  await registerViaUi(page, uniqueCredentials(info, 'DailyDate'))
  const today = await (await page.request.get('/api/today', { headers: await xsrfHeader(page) })).json()
  const next = new Date(`${today.date}T12:00:00Z`)
  next.setUTCDate(next.getUTCDate() + 1)
  const date = next.toISOString().slice(0, 10)
  const form = page.getByRole('form', { name: 'Quick capture' })
  await form.getByRole('textbox').fill('Tomorrow only')
  await pickDate(page, 'Date', date)
  await expect(form.getByRole('textbox')).toHaveValue('Tomorrow only')
  await form.getByRole('button', { name: 'Add', exact: true }).click()
  await expect(page.getByText('Added to this day.', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Open plan', exact: true }).click()
  await expect(page).toHaveURL(`/planner?date=${date}`)
  await expect(page.getByRole('listitem', { name: 'Tomorrow only', exact: true })).toBeVisible()
  await page.goto('/')
  await expect(page.getByRole('form', { name: 'Quick capture' })).toBeVisible()
  await expect(page.getByRole('listitem', { name: 'Tomorrow only', exact: true })).toHaveCount(0)
})

test('Today habit check-in and undo preserve weekly progress', async ({ page }, info) => {
  await registerViaUi(page, uniqueCredentials(info, 'DailyHabit'))
  const headers = await xsrfHeader(page)
  const response = await page.request.post('/api/habits', { headers, data: {
    name: 'Read a little', kind: 'habit', mode: 'yes_no', schedule_type: 'weekly_target', weekly_target: 3,
  } })
  expect(response.status()).toBe(201)
  await page.reload()
  const habit = page.getByRole('listitem', { name: 'Read a little', exact: true })
  await habit.getByRole('button', { name: 'Mark Read a little as done', exact: true }).click()
  await expect(habit).toContainText('1 of 3 this week')
  await page.reload()
  await expect(habit).toContainText('1 of 3 this week')
  await habit.getByRole('button', { name: 'Clear Read a little result', exact: true }).click()
  await expect(habit).toContainText('0 of 3 this week')
  await page.getByText('Daily totals & recent progress', { exact: true }).click()
  await expect(page.getByRole('region', { name: 'Daily completion summary' })).toContainText('0%')
})

test('inbox options, search and task details keep optional controls out of the way', async ({ page }, info) => {
  await registerViaUi(page, uniqueCredentials(info, 'DailyInbox'))
  const form = page.getByRole('form', { name: 'Quick capture' })
  await form.getByText('Task for this day · change', { exact: true }).click()
  await chooseOption(form, 'When', 'Inbox')
  await form.getByRole('textbox').fill('Repair the bike')
  await form.getByRole('button', { name: 'Add', exact: true }).click()
  await expect(page.getByText('Saved to your inbox in Tasks.', { exact: true })).toBeVisible()
  await page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('link', { name: 'Tasks', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Set up AI', exact: true })).toBeHidden()
  const search = page.getByRole('searchbox', { name: 'Find a task or idea' })
  await search.fill('missing')
  await expect(page.getByText('No matching items. Try another name.')).toBeVisible()
  await search.fill('bike')
  await page.getByRole('button', { name: 'Start Repair the bike', exact: true }).click()
  const item = page.getByRole('listitem', { name: 'Repair the bike', exact: true })
  await expect(item.getByRole('button', { name: 'Delete Repair the bike', exact: true })).toBeHidden()
  await item.getByText('Details & subtasks', { exact: true }).click()
  const today = await (await page.request.get('/api/today', { headers: await xsrfHeader(page) })).json()
  await pickDate(page, 'Plan Repair the bike', today.date)
  await expect(item).toContainText(today.date)
  await page.goto('/')
  await expect(page.getByRole('listitem', { name: 'Repair the bike', exact: true })).toBeVisible()
  await expectNoHorizontalOverflow(page)
})

test('validation preserves capture text and offline capture survives recovery', async ({ page }, info) => {
  test.setTimeout(60_000)
  await registerViaUi(page, uniqueCredentials(info, 'DailyOffline'))
  const form = page.getByRole('form', { name: 'Quick capture' })
  await expect(page.getByText(/No tasks or time blocks/)).toBeVisible()
  await page.route('**/api/storage/items', async route => {
    if (route.request().method() !== 'POST') return route.continue()
    await route.fulfill({ status: 422, contentType: 'application/json', body: JSON.stringify({ message: 'Invalid', errors: { title: ['Choose another title.'] } }) })
  })
  await form.getByRole('textbox').fill('Keep my text')
  await form.getByRole('button', { name: 'Add', exact: true }).click()
  await expect(form.getByText('Choose another title.')).toBeVisible()
  await expect(form.getByRole('textbox')).toHaveValue('Keep my text')
  await page.unroute('**/api/storage/items')
  const api = /^https?:\/\/[^/]+\/api\//
  await page.route(api, route => route.abort('internetdisconnected'))
  await form.getByRole('textbox').fill('Offline walk')
  await form.getByRole('button', { name: 'Add', exact: true }).click()
  await expect(page.getByRole('listitem', { name: 'Offline walk', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('listitem', { name: 'Offline walk', exact: true })).toBeVisible()
  await page.unroute(api)
  await expect.poll(async () => {
    const response = await page.request.get('/api/storage/items', { headers: await xsrfHeader(page) })
    return (await response.json()).data.filter((item: { title: string }) => item.title === 'Offline walk').length
  }, { timeout: 20_000 }).toBe(1)
})
