import { expect, test } from '@playwright/test'
import { registerViaUi, uniqueCredentials, xsrfHeader } from '../support/auth'
import { chooseOption, expectNoHorizontalOverflow } from './support'

test('water and unnamed meals can be recorded without creating catalogue entries', async ({ page }, info) => {
  await registerViaUi(page, uniqueCredentials(info, 'WaterUX'), { redirectTo: '/nutrition' })
  const water = page.getByRole('form', { name: 'Water', exact: true })
  await water.getByLabel('Water, ml').fill('500')
  await water.getByRole('button', { name: 'Log water' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Meal logged.' })).toBeVisible()
  const meals = page.getByRole('list', { name: 'Meals', exact: true })
  await expect(meals.getByRole('listitem', { name: 'Plain water', exact: true })).toBeVisible()
  const form = page.getByRole('form', { name: 'Log meal', exact: true })
  await form.getByRole('button', { name: 'Add food or drink' }).click()
  await chooseOption(form, 'Food or drink 1', 'Plain water')
  await expect(form.getByText('Millilitres', { exact: true }).first()).toBeVisible()
  await form.getByLabel('Entry 1 quantity').fill('250')
  await form.getByRole('button', { name: 'Log meal', exact: true }).click()
  await expect(meals.getByRole('listitem', { name: 'Plain water', exact: true })).toHaveCount(2)
  await page.reload()
  await expect(page.getByRole('region', { name: 'Nutrition progress' })).toContainText('750 ml')
  await expect(page.getByRole('form', { name: 'Create recipe' })).toBeHidden()
  await expectNoHorizontalOverflow(page)
})

test('gram targets apply to an already opened day and survive reload', async ({ page }, info) => {
  await registerViaUi(page, uniqueCredentials(info, 'GramUX'), { redirectTo: '/nutrition' })
  const settings = page.getByRole('form', { name: 'Target settings', exact: true })
  await settings.getByLabel('Protein, g/day').fill('35')
  await settings.getByLabel('Fat, g/day').fill('70')
  await settings.getByLabel('Carbohydrates, g/day').fill('210')
  await settings.getByRole('button', { name: 'Save and apply to this day' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Target settings saved and applied to this day.' })).toBeVisible()
  const progress = page.getByRole('region', { name: 'Nutrition progress' })
  await expect(progress).toContainText('35 g')
  await expect(progress).toContainText('70 g')
  await expect(progress).toContainText('210 g')
  await page.reload()
  await expect(settings.getByLabel('Fat, g/day')).toHaveValue('70')
  await chooseOption(settings, 'Set macro targets in', 'Percent of calculated calories')
  await settings.getByRole('button', { name: 'Save and apply to this day' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Target settings saved and applied to this day.' })).toBeVisible()
  await expect(progress).not.toContainText('70 g')
  await expectNoHorizontalOverflow(page)
  await page.getByRole('button', { name: 'RU', exact: true }).click()
  const save = page.getByRole('button', { name: 'Сохранить для этого дня', exact: true })
  await expect(save).toBeVisible()
  const saveBox = (await save.boundingBox())!
  expect(saveBox.width).toBeGreaterThan(150)
  expect(saveBox.height).toBeLessThan(100)
  await expectNoHorizontalOverflow(page)
})

test('sleep has an automatic name and all repeating schedules can have no end date', async ({ page }, info) => {
  await registerViaUi(page, uniqueCredentials(info, 'ScheduleUX'), { redirectTo: '/routines' })
  const sleep = page.getByRole('form', { name: 'Create sleep plan', exact: true })
  await expect(sleep.getByText('Dates are optional.', { exact: false })).toBeVisible()
  await sleep.getByRole('button', { name: 'Create sleep plan', exact: true }).click()
  await expect(page.getByRole('listitem', { name: 'Sleep', exact: true })).toBeVisible()
  const headers = await xsrfHeader(page)
  const data = await (await page.request.get('/api/sleep', { headers })).json()
  expect(JSON.stringify(data)).toContain('"ends_on":null')
  const routine = page.getByRole('form', { name: 'Create routine', exact: true })
  await routine.getByLabel('Name', { exact: true }).fill('Stretch every day')
  await routine.getByRole('button', { name: 'Create routine', exact: true }).click()
  await expect(page.getByRole('listitem', { name: 'Stretch every day', exact: true })).toBeVisible()
  await page.goto('/habits')
  await page.getByRole('button', { name: 'New habit', exact: true }).click()
  const habit = page.getByRole('form', { name: 'Create habit', exact: true })
  await habit.getByLabel('Name', { exact: true }).fill('Read')
  await expect(habit.getByText('Dates are optional.', { exact: false })).toBeVisible()
  await habit.getByRole('button', { name: 'Create habit', exact: true }).click()
  await expect(page.getByRole('listitem', { name: 'Read', exact: true })).toBeVisible()
  await expectNoHorizontalOverflow(page)
})

test('grouped budget amounts are saved at the intended scale', async ({ page }, info) => {
  await registerViaUi(page, uniqueCredentials(info, 'BudgetUX'), { redirectTo: '/finance' })
  await page.getByRole('tab', { name: 'Categories', exact: true }).click()
  await expect(page.getByRole('option', { name: 'No parent category', exact: true })).toBeAttached()
  await page.getByRole('tab', { name: 'Budgets', exact: true }).click()
  const budget = page.getByRole('form', { name: 'Budget editor', exact: true })
  await budget.getByLabel('Monthly limit').fill('15, 000')
  const saved = page.waitForResponse(response => response.url().includes('/api/finance/budgets') && response.request().method() === 'POST')
  await budget.getByRole('button', { name: 'Add budget', exact: true }).click()
  const response = await saved
  expect(response.ok()).toBeTruthy()
  expect((await response.json()).data.limit_amount).toBe('15000.0000')
  await page.reload()
  await expect(page.getByRole('article')).toContainText('15,000')
  await expectNoHorizontalOverflow(page)
})

test('goals, workout metrics and expanded AI guidance remain readable on narrow screens', async ({ page }, info) => {
  await page.setViewportSize({ width: info.project.name === 'mobile' ? 320 : 900, height: 900 })
  await registerViaUi(page, uniqueCredentials(info, 'ReadableUX'), { redirectTo: '/goals' })
  const form = page.getByRole('form', { name: 'Create goal', exact: true })
  await form.getByLabel('Name', { exact: true }).fill('Reshape my daily schedule')
  await form.getByLabel('Description', { exact: true }).fill('A readable goal with enough space for its description and actions.')
  await form.getByRole('button', { name: 'Create goal', exact: true }).click()
  const copy = page.getByRole('listitem', { name: 'Reshape my daily schedule', exact: true }).locator('.management-copy')
  await expect(copy).toBeVisible()
  expect((await copy.boundingBox())!.width).toBeGreaterThan(180)
  await expectNoHorizontalOverflow(page)
  await page.goto('/workouts')
  const metrics = page.locator('.workout-record-metrics .metric')
  await expect(metrics).toHaveCount(3)
  for (const metric of await metrics.all()) expect((await metric.boundingBox())!.width).toBeGreaterThanOrEqual(140)
  await expectNoHorizontalOverflow(page)
  await page.goto('/storage')
  await page.locator('.storage-ai-details > summary').click()
  const setup = page.getByRole('link', { name: 'Set up AI', exact: true })
  await expect(setup).toBeVisible()
  const setupBox = (await setup.boundingBox())!
  expect(setupBox.width).toBeGreaterThanOrEqual(44)
  // Includes the 44px touch target; a letter-per-line link is much taller.
  expect(setupBox.height).toBeLessThanOrEqual(60)
  await expectNoHorizontalOverflow(page)
})
