import { expect, test } from '@playwright/test'
import { registerViaUi, uniqueCredentials } from '../support/auth'
import { chooseOption, expectNoHorizontalOverflow, pickDate } from '../interface/support'
import { collectRuntimeIssues, expectNoRuntimeIssues } from '../core-daily-loop/support'

const todayDate = new Date()
const today = todayDate.toISOString().slice(0, 10)
const todayDayOfMonth = String(todayDate.getUTCDate())
const courseEnd = new Date(Date.now() + (7 * 24 * 60 * 60 * 1000)).toISOString().slice(0, 10)

async function createWallet(page: import('@playwright/test').Page, name: string): Promise<void> {
  await page.getByTestId('finance-tab-accounts').click()
  const form = page.getByRole('form', { name: 'Account editor' })
  await form.getByLabel('Name').fill(name)
  await form.getByLabel('Opening balance').fill('1000.0000')
  await form.getByRole('button', { name: 'Add account' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Account created.' })).toBeVisible()
  await expect(page.getByText(name, { exact: true })).toBeVisible()
  await page.waitForLoadState('networkidle')
}

test('debt payment reversal fund schedule goal and unified goal survive reload', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'The full transactional journey runs once; compact surfaces have a dedicated visual matrix.')
  test.setTimeout(300_000)
  page.setDefaultTimeout(10_000)
  await registerViaUi(page, uniqueCredentials(testInfo, 'FinanceCommitments'), { redirectTo: '/finance' })
  const issues = collectRuntimeIssues(page)
  await createWallet(page, 'Commitment wallet')

  await page.getByTestId('finance-tab-debts').click()
  const counterparty = page.getByRole('form', { name: 'Counterparty editor' })
  await counterparty.getByRole('textbox', { name: 'Counterparty', exact: true }).fill('North Bank')
  await counterparty.getByRole('button', { name: 'Add counterparty' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Counterparty created.' })).toBeVisible()

  const debtEditor = page.getByRole('form', { name: 'Debt editor' })
  await debtEditor.getByLabel('Name').fill('Laptop loan')
  await debtEditor.getByLabel('Original principal').fill('300.0000')
  await debtEditor.getByLabel('Currency').selectOption('UAH')
  await debtEditor.getByLabel('Originated on').fill(today)
  await debtEditor.getByLabel('Account').selectOption({ label: 'Commitment wallet' })
  await debtEditor.getByLabel('Category').selectOption({ label: 'Food' })
  await debtEditor.getByRole('button', { name: 'Add debt' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Debt created.' })).toBeVisible()

  let debt = page.getByRole('article').filter({ hasText: 'Laptop loan' }).first()
  await debt.getByRole('button', { name: 'Edit' }).click()
  await debtEditor.getByLabel('Name').fill('Laptop loan updated')
  await debtEditor.getByRole('button', { name: 'Save debt' }).click()
  debt = page.getByRole('article').filter({ hasText: 'Laptop loan updated' }).first()
  await expect(debt).toBeVisible()

  await debt.getByRole('button', { name: 'Record payment' }).click()
  const payment = debt.getByRole('form', { name: 'Debt payment editor' })
  await payment.getByLabel('Amount').fill('100.0000')
  await payment.getByRole('button', { name: 'Save payment' }).click()
  await expect(debt).toContainText('200.00')
  await debt.getByText(/Payment history/).click()
  const transactionLink = debt.locator('a[href*="tab=activity"]').first()
  await transactionLink.click()
  await expect(page.getByTestId('finance-tab-activity')).toHaveAttribute('aria-selected', 'true')
  const focusedTransaction = page.locator('[data-finance-transaction].is-deep-linked')
  await expect(focusedTransaction).toBeVisible()
  page.once('dialog', (dialog) => dialog.accept('Corrected payment'))
  await focusedTransaction.getByRole('button', { name: 'Reverse' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Reversal posted.' })).toBeVisible()

  await page.getByTestId('finance-tab-debts').click()
  debt = page.getByRole('article').filter({ hasText: 'Laptop loan updated' }).first()
  await expect(debt).toContainText('300.00')
  await debt.getByText(/Payment history/).click()
  await expect(debt).toContainText('Reversed')

  await page.getByTestId('finance-tab-funds').click()
  const fundEditor = page.getByRole('form', { name: 'Saving fund editor' })
  await fundEditor.getByLabel('Name').fill('Rainy day')
  await fundEditor.getByLabel('Currency').selectOption('UAH')
  await fundEditor.getByLabel('Backing account').selectOption({ label: 'Commitment wallet' })
  await fundEditor.getByLabel('Target amount').fill('500.0000')
  await fundEditor.getByRole('button', { name: 'Add fund' }).click()
  let fund = page.getByRole('article').filter({ hasText: 'Rainy day' }).first()
  await fund.getByRole('button', { name: 'Move money' }).click()
  let movement = fund.getByRole('form', { name: 'Fund movement editor' })
  await movement.getByLabel('Amount').fill('200.0000')
  await movement.getByRole('button', { name: 'Save movement' }).click()
  await expect(fund).toContainText('200.00')
  await fund.getByText(/Movement history/).click()
  await fund.getByRole('button', { name: 'Reverse' }).click()
  await expect(fund).toContainText('Reversal')
  await expect(fund.locator('.finance-money')).toContainText('0.00')

  await fundEditor.getByLabel('Name').fill('Monthly cushion')
  await fundEditor.getByLabel('Currency').selectOption('UAH')
  await fundEditor.getByLabel('Backing account').selectOption({ label: 'Commitment wallet' })
  await fundEditor.getByLabel('Target amount').fill('100.0000')
  await fundEditor.getByLabel('Top-up rule').selectOption({ label: 'Fixed amount' })
  await fundEditor.getByLabel('Top-up amount').fill('25.0000')
  await fundEditor.getByLabel('Starts on').fill(today)
  await fundEditor.getByLabel('Day of month').fill(todayDayOfMonth)
  expect(await fundEditor.locator(':invalid').evaluateAll((elements) => elements.map((element) => ({
    label: element.parentElement?.textContent?.trim(),
    value: (element as HTMLInputElement).value,
    message: (element as HTMLInputElement).validationMessage,
  })))).toEqual([])
  await fundEditor.getByRole('button', { name: 'Add fund' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Saving fund created.' })).toBeVisible()
  fund = page.getByRole('article').filter({ hasText: 'Monthly cushion' }).first()
  const firstFundOccurrence = fund.locator('[data-finance-occurrence]').first()
  await firstFundOccurrence.getByRole('button', { name: 'Skip' }).click()
  await firstFundOccurrence.getByRole('button', { name: 'Clear skip' }).click()
  await expect(firstFundOccurrence.getByRole('button', { name: 'Top up' })).toBeVisible()
  await firstFundOccurrence.getByRole('button', { name: 'Top up' }).click()
  await expect(fund).toContainText('25.00')

  await page.getByTestId('finance-tab-goals').click()
  const goalEditor = page.getByRole('form', { name: 'Finance goal editor' })
  await goalEditor.getByLabel('Name').fill('Build monthly cushion')
  await goalEditor.getByLabel('Linked fund or debt').selectOption({ label: 'Monthly cushion' })
  await goalEditor.getByLabel('Milestones').fill('25, 50, 100')
  await goalEditor.getByRole('button', { name: 'Add goal' }).click()
  let goal = page.getByRole('article').filter({ hasText: 'Build monthly cushion' }).first()
  await expect(goal).toContainText('25.00')
  await goal.getByRole('button', { name: 'Edit' }).click()
  await goalEditor.getByLabel('Name').fill('Build cushion safely')
  await goalEditor.getByRole('button', { name: 'Save goal' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Finance goal updated.' })).toBeVisible()
  await expect(page.getByRole('article').filter({ hasText: 'Build cushion safely' })).toBeVisible()

  await page.goto('/goals')
  goal = page.getByRole('listitem', { name: 'Build cushion safely' })
  await expect(goal).toContainText('25.00')
  await goal.getByRole('link', { name: 'Open in Finance' }).click()
  await expect(page).toHaveURL(/\/finance\?tab=goals#finance-goal-\d+$/)
  await expect(page.locator('[id^="finance-goal-"]').filter({ hasText: 'Build cushion safely' })).toBeVisible()
  await page.reload()
  await expect(page.locator('[id^="finance-goal-"]').filter({ hasText: 'Build cushion safely' })).toBeVisible()
  await expectNoHorizontalOverflow(page)
  expectNoRuntimeIssues(issues)
})

test('purchase and restock expenses keep their source links without claiming stock arrival', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'The full transactional journey runs once; compact surfaces have a dedicated visual matrix.')
  test.setTimeout(300_000)
  page.setDefaultTimeout(10_000)
  await registerViaUi(page, uniqueCredentials(testInfo, 'FinanceSources'), { redirectTo: '/finance' })
  const issues = collectRuntimeIssues(page)
  await createWallet(page, 'Source wallet')

  await page.goto('/storage')
  const capture = page.getByRole('form', { name: 'Capture an item' })
  await chooseOption(capture, 'Type', 'Purchase')
  await capture.getByLabel('What is on your mind?').fill('Direct headphones')
  await capture.getByLabel('Estimate').fill('50.0000')
  await capture.getByRole('button', { name: 'Capture' }).click()
  let purchase = page.getByRole('listitem', { name: 'Direct headphones' })
  await purchase.getByRole('button', { name: 'Record direct expense' }).click()
  const expense = purchase.getByRole('form', { name: 'Purchase expense editor' })
  await chooseOption(expense, 'Account', 'Source wallet')
  await expense.getByLabel('Amount').fill('50.0000')
  await expense.getByRole('button', { name: 'Post expense' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Purchase expense recorded; the purchase is now bought.' })).toBeVisible()
  await expect(page.getByRole('listitem', { name: 'Direct headphones' })).toContainText('Bought')

  await page.goto('/finance?tab=activity')
  const purchaseFact = page.getByRole('listitem').filter({ hasText: 'Direct headphones' }).first()
  await page.waitForLoadState('networkidle')
  await purchaseFact.getByRole('link').click()
  await expect(page).toHaveURL(/\/storage\?item=\d+$/)
  await expect(page.getByRole('listitem', { name: 'Direct headphones' })).toHaveClass(/is-deep-linked/)

  await chooseOption(capture, 'Type', 'Purchase')
  await capture.getByLabel('What is on your mind?').fill('Installment tablet')
  await capture.getByLabel('Estimate').fill('120.0000')
  await capture.getByRole('button', { name: 'Capture' }).click()
  purchase = page.getByRole('listitem', { name: 'Installment tablet' })
  await purchase.getByRole('link', { name: 'Set up installments' }).click()
  await expect(page).toHaveURL(/\/finance\?tab=debts&purchase=\d+/)
  const purchaseId = await page.getByRole('form', { name: 'Debt editor' }).getByLabel('Purchase item ID').inputValue()
  expect(Number(purchaseId)).toBeGreaterThan(0)

  const counterparty = page.getByRole('form', { name: 'Counterparty editor' })
  await counterparty.getByRole('textbox', { name: 'Counterparty', exact: true }).fill('Device Store')
  await counterparty.getByRole('button', { name: 'Add counterparty' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Counterparty created.' })).toBeVisible()
  await expect(page.getByRole('form', { name: 'Debt editor' }).getByLabel('Counterparty')).toContainText('Device Store')
  const debt = page.getByRole('form', { name: 'Debt editor' })
  await debt.getByLabel('Name').fill('Tablet installments')
  await debt.getByLabel('Repayment mode').selectOption({ label: 'Fixed schedule' })
  await debt.getByLabel('Original principal').fill('120.0000')
  await debt.getByLabel('Currency').selectOption('UAH')
  await debt.getByLabel('Originated on').fill(today)
  await debt.getByLabel('Account').selectOption({ label: 'Source wallet' })
  await debt.getByLabel('Category').selectOption({ label: 'Food' })
  await debt.getByLabel('Installment amount').fill('40.0000')
  await debt.getByLabel('Installment count').fill('3')
  await debt.getByLabel('Day of month').fill(todayDayOfMonth)
  await debt.getByLabel('First due date').fill(today)
  await debt.getByRole('button', { name: 'Add debt' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Debt created.' })).toBeVisible()
  await expect(page.getByRole('article').filter({ hasText: 'Tablet installments' })).toBeVisible()
  await page.goto('/storage')
  await expect(page.getByRole('listitem', { name: 'Installment tablet' })).toContainText('Bought')

  await page.goto('/supplements')
  await page.getByRole('tab', { name: 'Catalogue' }).click()
  await page.getByRole('button', { name: 'Add reference' }).click()
  const reference = page.getByRole('form', { name: 'Supplement reference editor' })
  await reference.getByLabel('Name').fill('Restock magnesium')
  await reference.getByLabel('Package quantity').fill('30')
  await reference.getByRole('button', { name: 'Save' }).click()
  let supplement = page.getByRole('article').filter({ hasText: 'Restock magnesium' }).first()
  await supplement.getByRole('button', { name: 'Manage stock' }).click()
  const stock = page.getByRole('form', { name: 'Stock movement editor' })
  await stock.getByLabel('Quantity').fill('1')
  await stock.getByRole('button', { name: 'Save' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Stock movement recorded.' })).toBeVisible()
  await expect(page.getByText('1.000', { exact: false }).first()).toBeVisible()
  await page.getByRole('tab', { name: 'Courses' }).click()
  await page.getByRole('button', { name: 'Add course' }).click()
  const course = page.getByRole('form', { name: 'Course editor' })
  await course.getByLabel('Course name').fill('Restock course')
  await pickDate(page, 'Starts on', today)
  await pickDate(page, 'Ends on', courseEnd)
  await course.getByRole('button', { name: 'Save' }).click()
  await expect(page.getByRole('article').filter({ hasText: 'Restock course' })).toBeVisible()
  await page.getByRole('tab', { name: 'Catalogue' }).click()
  supplement = page.getByRole('article').filter({ hasText: 'Restock magnesium' }).first()
  await expect(supplement).toContainText('Restock suggested')
  await supplement.getByRole('button', { name: 'Record Finance expense' }).click()
  const restockExpense = supplement.locator('form.finance-form')
  await restockExpense.getByLabel('Account').selectOption({ label: 'Source wallet · UAH' })
  await restockExpense.getByLabel('Amount').fill('25.0000')
  await restockExpense.getByRole('button', { name: 'Post expense' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Expense recorded. Stock is unchanged until you record a restock movement.' })).toBeVisible()
  await expect(supplement).toContainText('Restock suggested')
  await expect(supplement).toContainText('1')
  await expect(supplement.getByRole('button', { name: 'Record Finance expense' })).toBeEnabled()

  await page.goto('/finance?tab=activity')
  const restockFact = page.getByRole('listitem').filter({ hasText: 'Restock magnesium' }).first()
  await page.waitForLoadState('networkidle')
  await restockFact.getByRole('link').click()
  await expect(page).toHaveURL(/\/supplements\?restock=\d+$/)
  await expect(page.getByRole('tab', { name: 'Stock' })).toHaveAttribute('aria-selected', 'true')
  await expect(page.locator('[data-restock-proposal].is-deep-linked')).toContainText('Restock suggested')
  await expectNoHorizontalOverflow(page)
  expectNoRuntimeIssues(issues)
})
